import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Navigation Bar */}
        <nav className="p-4 bg-gray-800 text-white flex justify-between items-center">
          <div>
            <Link href="/" className="text-lg font-semibold hover:underline">Home</Link>
          </div>
          <div>
            <Link href="/login" className="bg-blue-600 px-4 py-2 rounded-md hover:bg-blue-700 transition">Login</Link>
          </div>
        </nav>

        {/* Page Content */}
        {children}
      </body>
    </html>
  );
}
